apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: backstage
  namespace: core-component
  description: Backstage for Cloud Toulouse
  links:
    - url: https://github.com/laurentgrangeau/cloudtoulouse-backstage
      title: Backstage for Cloud Toulouse on GitHub
spec:
  owner: user:default/laurentgrangeau
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cloudtoulouse-backstage
  description: Backstage app for Cloud Toulouse
  annotations:
    google.com/cloudbuild-project-slug: lgu-demos
    google.com/cloudbuild-trigger-name: cloudtoulouse-backstage
    google.com/cloudbuild-location: europe-west1
    backstage.io/kubernetes-id: backstage
    backstage.io/kubernetes-namespace: backstage
spec:
  type: website
  owner: user:default/laurentgrangeau
  lifecycle: experimental
  system: core-component/backstage
