apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cloudtoulouse-backstage
  description: Backstage app for Cloud Toulouse.
  # Example for optional annotations
  annotations:
    google.com/cloudbuild-project-slug: lgu-demos
    google.com/cloudbuild-trigger-name: cloudtoulouse-backstage
    google.com/cloudbuild-location: europe-west1
    backstage.io/kubernetes-id: backstage-cloudtoulouse
spec:
  type: website
  owner: laurent.grangeau@gmail.com
  lifecycle: experimental
