# This Cloud Build pipeline builds + deploys the Backstage instance (backstage/) to the GKE admin cluster. 
steps:
# Build Backstage container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "europe-west1-docker.pkg.dev/lgu-demos/backstage/backstage:$COMMIT_SHA", "packages/backend"]
# Build the backstage app with yarn https://backstage.io/docs/deployment/docker/#host-build 
- name: "node:20"
  entrypoint: yarn
  args:
    - install
# yarn upgrade
- name: "node:20"
  entrypoint: yarn
  args:
    - upgrade
# yarn tsc
- name: "node:20"
  entrypoint: yarn
  args:
    - tsc
# yarn build
- name: "node:20"
  entrypoint: yarn
  args:
    - build:backend
    - --config
    - ../../app-config.yaml
# Push Backstage container image 
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "europe-west1-docker.pkg.dev/lgu-demos/backstage/backstage:$COMMIT_SHA"]
# Set backstage image in Kubernetes deployment manifest using sed 
- name: "gcr.io/cloud-builders/gcloud"
  entrypoint: "bash"
  args:
  - "-c"
  - |
    sed -i 's|europe-west1-docker.pkg.dev/lgu-demos/backstage/backstage:latest|europe-west1-docker.pkg.dev/lgu-demos/backstage/backstage:$COMMIT_SHA|g' kubernetes/backstage-deployment.yaml
# Deploy Backstage to GKE
- name: "gcr.io/cloud-builders/kubectl"
  args:
  - "apply"
  - "-f"
  - "kubernetes/backstage-deployment.yaml"
  env:
  - "CLOUDSDK_COMPUTE_ZONE=europe-west1-c"
  - "CLOUDSDK_CONTAINER_CLUSTER=backstage"